# How to use MC simulation

The main entry point for MC simulation in the current code base is currently found in `chromo.mc.polymer_in_field`. This file shows the basic usage of that function.

# Navigate to top-level directory

In [1]:
## Navigate from directory containing notebook to main directiry ##

import sys
import os

print("Python executable location:")
print(sys.executable)
print()

print("Directory containing Jupyter notebook:")
print(os.getcwd())
print()

print("Main directory of chromo:")
os.chdir("../..")
print(os.getcwd())

Python executable location:
/Users/jwakim/anaconda3/bin/python

Directory containing Jupyter notebook:
/Users/jwakim/Documents/Wakim_Research/Scripts/chromo_forGit/chromo/doc/source

Main directory of chromo:
/Users/jwakim/Documents/Wakim_Research/Scripts/chromo_forGit/chromo


# Import modules

In [2]:
# Import built-in, third-party, local modules #

import importlib
from io import StringIO

import numpy as np
import pandas as pd

import chromo
import chromo.mc as mc
from chromo.components import Polymer
import chromo.marks
from chromo.fields import UniformDensityField

# Define the simulation

Begin by defining the components involved in the simulation.
This includes specifying the list of epigenetic marks (with attributes),
the list of polymers, and the field. Then run the Monte Carlo for the specified number of steps and save points, and save the output configurations. 

First specify what epigenetic marks should be used.

In [3]:
epimarks = [chromo.marks.get_by_name('HP1')]
#or just e.g. epimarks = [chromo.marks.hp1]
# making it a list is optional since there's only one element

In [4]:
epimarks

[Epigenmark(name='HP1', bind_energy=1, interaction_energy=1, chemical_potential=1)]

They are expected in a DataFrame format.

In [5]:
marks = chromo.marks.make_mark_collection(epimarks)

Now specify the initial state of the polymer(s). We will use just one here.

In [6]:
p = Polymer.straight_line_in_x('Chr-1', 10, 1, states=np.zeros((10,)), mark_names=['HP1'])

Finally create a field object to contain the polymers.

In [7]:
udf = UniformDensityField([p], marks, 10, 20, 30, 40, 50, 60)

I AM HERE
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
num_marks: 1
ind_corner: 0
DENSITY TOTAL
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
indf - ind0: 10
ind_mark: 0
STATES
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ind0: 0
indf: 10
why does states change so much???
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ind_corner: 1
DENSITY TOTAL
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
indf - ind0: 10
ind_mark: 0
STATES
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ind0: 0
indf: 10
why does states change so much???
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ind_corner: 2
DENSITY TOTAL
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
indf - ind0: 10
ind_mark: 0
STATES
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ind0: 0
indf: 10
why does states change so much???
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 

As per the docs of `chromo.util.reproducibility.make_reproducible`, check the `simulations.csv` file in the requested output folder (i.e. `{current working directory of this Notebook}/{output_dir}`) to see information about all simulations that have been run so far.

All inputs are saved in the output folder as well, for exact reproducibility.

# Run the simulation

In [8]:
mc.polymer_in_field([p], marks, udf, 1000, 10, output_dir='output')

CRANK-SHAFT MOVE
poly.states
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[None]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
HERE
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
num_marks: 1
ind_corner: 0
DENSITY TOTAL
[0. 0. 0. 0. 0. 0. 0.]
indf - ind0: 7
ind_mark: 0
STATES
[0. 0. 0. 0. 0. 0. 0.]
ind0: 3
indf: 10
why does states change so much???
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ind_corner: 1
DENSITY TOTAL
[0. 0. 0. 0. 0. 0. 0.]
indf - ind0: 7
ind_mark: 0
STATES
[0. 0. 0. 0. 0. 0. 0.]
ind0: 3
indf: 10
why does states change so much???
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ind_corner: 2
DENSITY TOTAL
[0. 0. 0. 0. 0. 0. 0.]
indf - ind0: 7
ind_mark: 0
STATES
[0. 0. 0. 0. 0. 0. 0.]
ind0: 3
indf: 10
why does states change so much???
[[0.]
 [0.]
 [

/Users/jwakim/Documents/Wakim_Research/Scripts/chromo_forGit/chromo/chromo/fields.py:178: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  return pd.Series(rows).to_csv(path, header=None)
/Users/jwakim/Documents/Wakim_Research/Scripts/chromo_forGit/chromo/chromo/mc/__init__.py:58: UserWarning: The random seed is currently ignored.
  warnings.warn("The random seed is currently ignored.", UserWarning)


TypeError: object of type 'NoneType' has no len()

Here's an alternative implementation that takes only "simple" inputs:

In [ ]:
# mc.simple_mc(num_polymers=5, num_beads=10, bead_length=1, num_marks=2, num_save_mc=1000, num_saves=10,
#             x_width=10, nx=1, y_width=10, ny=1, z_width=10, nz=1, random_seed=0, output_dir='output_simple')